
import React, { useState, useMemo } from 'react';
import { Link } from 'react-router-dom';

const sqlScript = `-- Agri-Smart Go Supabase Setup Script (Idempotent)
-- This script can be run multiple times without causing errors.

-- 1. Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Create ENUM types if they don't exist
DO $$ BEGIN CREATE TYPE public.employee_status AS ENUM ('Active', 'Inactive'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.order_status AS ENUM ('Quote', 'Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.transaction_type AS ENUM ('Income', 'Expense'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.user_role AS ENUM ('Admin', 'Farm Manager', 'Accountant', 'Sales', 'Worker'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.user_status AS ENUM ('Active', 'Inactive'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.plot_status AS ENUM ('ว่าง', 'เตรียมดิน', 'กำลังเติบโต', 'พร้อมเก็บเกี่ยว', 'เก็บเกี่ยวแล้ว'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.activity_type AS ENUM ('เตรียมดิน', 'ปลูก', 'ใส่ปุ๋ย', 'รดน้ำ', 'กำจัดวัชพืช', 'เก็บเกี่ยว'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.activity_status AS ENUM ('วางแผน', 'กำลังดำเนินการ', 'เสร็จสิ้น'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.asset_status AS ENUM ('ใช้งาน', 'ซ่อมบำรุง', 'จำหน่ายแล้ว'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.payment_status AS ENUM ('ค้างชำระ', 'ชำระแล้ว', 'ค้างจ่าย', 'จ่ายแล้ว'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.investment_status AS ENUM ('วางแผน', 'อนุมัติแล้ว', 'กำลังดำเนินการ', 'เสร็จสิ้น'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.risk_level AS ENUM ('ต่ำ', 'ปานกลาง', 'สูง'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.risk_category AS ENUM ('ภัยธรรมชาติ', 'โรคระบาด', 'ราคาตลาด', 'การดำเนินงาน'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.risk_status AS ENUM ('ระบุแล้ว', 'กำลังจัดการ', 'จัดการแล้ว', 'เกิดขึ้นจริง'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.device_status AS ENUM ('Online', 'Offline', 'Needs Setup'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.supply_category AS ENUM ('ปุ๋ย', 'ยาฆ่าแมลง', 'เมล็ดพันธุ์', 'เครื่องมือ', 'อื่นๆ'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.supply_unit AS ENUM ('กิโลกรัม', 'ลิตร', 'ถุง', 'ชิ้น', 'ขวด'); EXCEPTION WHEN duplicate_object THEN null; END $$;


-- 3. Create Tables if they don't exist

CREATE TABLE IF NOT EXISTS public.company_info (
    id bigint generated by default as identity primary key,
    name text not null,
    address text,
    phone text,
    email text,
    "taxId" text,
    "logoUrl" text,
    "bankAccount" jsonb
);

CREATE TABLE IF NOT EXISTS public.supply_items (
    id uuid default uuid_generate_v4() primary key,
    name text not null,
    category public.supply_category,
    supplier text,
    quantity numeric,
    unit public.supply_unit,
    unit_price numeric,
    reorder_level integer,
    last_updated timestamptz not null default now()
);

-- Note for existing users: This changes the employee ID to a standard format (e.g., EMP001).
-- If you have an old 'employees' table with a 'uuid' type for 'id', you must drop it before re-running this script for the change to take effect.
-- To do so, run: DROP TABLE public.employees;
CREATE SEQUENCE IF NOT EXISTS employee_id_seq;
CREATE TABLE IF NOT EXISTS public.employees (
    id text primary key not null default 'EMP' || lpad(nextval('employee_id_seq')::text, 3, '0'),
    name text not null,
    nickname text,
    dob date,
    age integer,
    "idCard" text,
    address text,
    phone text,
    "startDate" date,
    position text,
    salary numeric,
    status public.employee_status
);


CREATE TABLE IF NOT EXISTS public.customers (
    id uuid default uuid_generate_v4() primary key,
    name text not null,
    "contactPerson" text,
    email text,
    phone text,
    address text,
    "joinDate" date
);

CREATE TABLE IF NOT EXISTS public.products (
    id uuid default uuid_generate_v4() primary key,
    product_code text unique,
    name text not null,
    category text,
    "unitPrice" numeric,
    "costPrice" numeric,
    "stockQuantity" integer,
    "lowStockThreshold" integer
);

CREATE TABLE IF NOT EXISTS public.sales_orders (
    id uuid default uuid_generate_v4() primary key,
    order_code text not null unique,
    "customerId" uuid references public.customers(id),
    "customerName" text,
    "orderDate" date,
    status public.order_status,
    "totalAmount" numeric
);

CREATE TABLE IF NOT EXISTS public.order_items (
    id bigint generated by default as identity primary key,
    order_id uuid not null references public.sales_orders(id) on delete cascade,
    "productId" uuid not null references public.products(id),
    product_code text,
    "productName" text,
    quantity integer,
    "unitPrice" numeric
);

CREATE TABLE IF NOT EXISTS public.financial_transactions (
    id uuid default uuid_generate_v4() primary key,
    date date,
    description text,
    type public.transaction_type,
    category text,
    amount numeric
);

CREATE TABLE IF NOT EXISTS public.plots (
    id uuid default uuid_generate_v4() primary key,
    name text,
    crop text,
    "plantingDate" date,
    "expectedHarvestDate" text,
    status public.plot_status,
    size numeric
);

CREATE TABLE IF NOT EXISTS public.farm_activities (
    id uuid default uuid_generate_v4() primary key,
    date date,
    "activityType" public.activity_type,
    "plotId" uuid references public.plots(id),
    "plotName" text,
    "assignedTo" text,
    status public.activity_status
);

CREATE TABLE IF NOT EXISTS public.iot_devices (
    id uuid default uuid_generate_v4() primary key,
    device_id text not null unique,
    name text,
    plot_id uuid references public.plots(id) on delete set null,
    sensor_type text,
    status public.device_status,
    last_heartbeat timestamptz
);

CREATE TABLE IF NOT EXISTS public.assets (
    id uuid default uuid_generate_v4() primary key,
    name text,
    "purchaseDate" date,
    "purchaseCost" numeric,
    "usefulLife" integer,
    "salvageValue" numeric,
    "depreciationMethod" text default 'Straight-line',
    status public.asset_status
);

CREATE TABLE IF NOT EXISTS public.receivables (
    id uuid default uuid_generate_v4() primary key,
    "customerName" text,
    "invoiceId" text,
    "issueDate" date,
    "dueDate" date,
    amount numeric,
    status public.payment_status
);

CREATE TABLE IF NOT EXISTS public.payables (
    id uuid default uuid_generate_v4() primary key,
    "vendorName" text,
    "invoiceId" text,
    "issueDate" date,
    "dueDate" date,
    amount numeric,
    status public.payment_status
);

CREATE TABLE IF NOT EXISTS public.investment_projects (
    id uuid default uuid_generate_v4() primary key,
    name text,
    description text,
    "investmentCost" numeric,
    "expectedRevenue" numeric,
    status public.investment_status
);

CREATE TABLE IF NOT EXISTS public.risk_items (
    id uuid default uuid_generate_v4() primary key,
    "riskName" text,
    category public.risk_category,
    likelihood public.risk_level,
    impact public.risk_level,
    "mitigationPlan" text,
    status public.risk_status
);

CREATE TABLE IF NOT EXISTS public.users (
    id uuid default uuid_generate_v4() primary key,
    name text,
    email text UNIQUE,
    role public.user_role,
    status public.user_status,
    "avatarUrl" text
);

-- 4. Set up Row Level Security (RLS) policies
-- DROP IF EXISTS is used to make sure the script can be re-run to update policies.
ALTER TABLE public.company_info ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.company_info;
CREATE POLICY "Allow authenticated users" ON public.company_info FOR ALL TO authenticated USING (true);

ALTER TABLE public.supply_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.supply_items;
CREATE POLICY "Allow authenticated users" ON public.supply_items FOR ALL TO authenticated USING (true);

ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.employees;
CREATE POLICY "Allow authenticated users" ON public.employees FOR ALL TO authenticated USING (true);

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.customers;
CREATE POLICY "Allow authenticated users" ON public.customers FOR ALL TO authenticated USING (true);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.products;
CREATE POLICY "Allow authenticated users" ON public.products FOR ALL TO authenticated USING (true);

ALTER TABLE public.sales_orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.sales_orders;
CREATE POLICY "Allow authenticated users" ON public.sales_orders FOR ALL TO authenticated USING (true);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.order_items;
CREATE POLICY "Allow authenticated users" ON public.order_items FOR ALL TO authenticated USING (true);

ALTER TABLE public.financial_transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.financial_transactions;
CREATE POLICY "Allow authenticated users" ON public.financial_transactions FOR ALL TO authenticated USING (true);

ALTER TABLE public.plots ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.plots;
CREATE POLICY "Allow authenticated users" ON public.plots FOR ALL TO authenticated USING (true);

ALTER TABLE public.farm_activities ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.farm_activities;
CREATE POLICY "Allow authenticated users" ON public.farm_activities FOR ALL TO authenticated USING (true);

ALTER TABLE public.assets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.assets;
CREATE POLICY "Allow authenticated users" ON public.assets FOR ALL TO authenticated USING (true);

ALTER TABLE public.receivables ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.receivables;
CREATE POLICY "Allow authenticated users" ON public.receivables FOR ALL TO authenticated USING (true);

ALTER TABLE public.payables ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.payables;
CREATE POLICY "Allow authenticated users" ON public.payables FOR ALL TO authenticated USING (true);

ALTER TABLE public.investment_projects ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.investment_projects;
CREATE POLICY "Allow authenticated users" ON public.investment_projects FOR ALL TO authenticated USING (true);

ALTER TABLE public.risk_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.risk_items;
CREATE POLICY "Allow authenticated users" ON public.risk_items FOR ALL TO authenticated USING (true);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.users;
CREATE POLICY "Allow authenticated users" ON public.users FOR ALL TO authenticated USING (true);

ALTER TABLE public.iot_devices ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users" ON public.iot_devices;
CREATE POLICY "Allow authenticated users" ON public.iot_devices FOR ALL TO authenticated USING (true);


-- 5. Insert Initial Data if it doesn't exist

-- Insert company info only if the table is empty
INSERT INTO public.company_info (name, address, phone, email, "taxId", "logoUrl", "bankAccount")
SELECT 'บริษัท อะกริ-สมาร์ท โก ฟาร์ม จำกัด', '123 หมู่ 5 ถนนพัฒนาการ แขวงสวนหลวง เขตสวนหลวง กรุงเทพมหานคร 10250', '02-987-6543', 'contact@agri-smart-go.th', '0105567890123', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAABfGlDQ1BJQ0MgUHJvZmlsZQAAKJFjYGASSSwoyGFhYGDIzSspCnJ3UoiIjFJgf8LAwSDCBAsoYNDg2M3AyQcc3Bwgd3RwV3FwcnBwYGFgYWhjYNNgYOBhYGBgc2BgiMiYwMDAsYmZgwUTgZcRgwMDBkZWBkYGDQY2NCAm4sAgSwSg3gYmBiYGNhYmBkaI9QyQd3D0cXExcXDx8XFyefeD0QgNCQ0JDRkdIS0hLSk9JT0jPzCgQEhQyFjoqOCo8Ii4iPiFBQVtLW0dXR1tHX0DEwsbA1MLaytrB3sHRxcfPz8wMDAoZKhkqKSY5LTUtPSM/IKEgqKCk4qiqoq6hr6BoZmJmaW5hbWVnY29g7OLs4u7h6eHp4+/gFBAUGBcYGhkVGx4bHJscmxzZHJ+AxRAhJAkKAiGBsY2BguMDCgYmBjQW5DAwMHgwcmBjsMPgw9DBEwMrgynDO8MewzcDD4Mfgz/DEgMMQxZDDsMaww+DP4MvAwKDA4MjAyvDAEMnwwODBIMiwwYGBgYWBgYBBgZ/38AAwBZyBeQv2UZJwAAAaNJREFUeF7t2E1uE0EUQNEqFV2kSg90E+kF6AnpCegh6Ak6iQqToC4lIEp/l+T10kP7d2aGZ3szS+cQAmOMMcYYY4wxxtgvXf41D02/tC/3u9t6l3I5P/338v/B+xS/u1wO5S5Xb7VbrL5v3e1cTgf939lu1fP9eZxfz4cDA6/Xy+3Wfr8fDIbwPG8wGEQiEdZl9/u9Xq/L5XJZlgzDGA6HruvSNHVd93g8HMfBYDD4fr+madrtdhAEGIYBgLqu27bt9/s8z1/v147jqKoqiqJarYIg6LquKIpSqYTjOOI4WpbV6XSyLAuCYLPZEREREfl+v0ajIcuyruvSNEEQxsbGGIYhCALbtgRB0HWdy+VIkqTValUqlWq1+uPHj0lSpGlKknS5XJxzOp14nr/+/fsAQNd17XY7lUpFo9HBYDDP8/V63XA4zLJsGIZcLu/1+imKgiB4uVzSNE3TtMvlIggCEARBEBqNhmVZOI5DkiRBEJaWlvJ8vV6vy+X6+fPnLMumadputzMM8zy/3+/z+YhEItI0XZaVZZlSqRCLxX6/XyqVSqVSWZZtNptOp3M4HCiKgiAIwzASidRqtVKpRDAYVFWVSqVKpRLHsVarxXEclmVRFCWRSCRJgmFZtVqNMHa73RzHDYbDYDDY7XbD4TCZTGRZlqapqqpSqZAkSTqdDgQCAACCIJlMhmEYy7JgGJbNZmmazuVygiBoNpuxbZumaTweg8FgGIbPnz/P5XJZlpumCYJgNpsBAMuyPM8Hg8EslwsEAiiKYjabPM9jsVjiOM7n88u+l9lsZllWVZWIomi12mw2i2H4l//p/8t3X6/XbrdLknQ6nWAwwOv1yuVygiDY7fayLNvtVp7nGIYpl8vD4bAsy7Isy7KMYRhRFIVCoaqqpmnD4XCQyWQymQxBEBiG0ev1GIbxPG82m6VSKdI03Wi0bdu23W6nKMrlcslkMsuykCQxGo26rg8EApZlybJkjP3J8d/o/kYwGEQiEfz+4tLSoiaTsVgsHMfJstxutzMMm83mWJaVSqWmabPZLFmWpmmMfT3+Bxgj/wN7s78b/Z88vQAAAABJRU5ErkJggg==',
    jsonb_build_object('bankName', 'ธนาคารกสิกรไทย', 'accountName', 'บริษัท อะกริ-สมาร์ท โก ฟาร์ม จำกัด', 'accountNumber', '123-4-56789-0')
WHERE NOT EXISTS (SELECT 1 FROM public.company_info);

-- Insert user only if the email doesn't exist. This is more robust than ON CONFLICT.
INSERT INTO public.users (name, email, role, status)
SELECT 'สมชาย เกษตรกร', 'demo@agri-smart.go', 'Admin', 'Active'
WHERE NOT EXISTS (SELECT 1 FROM public.users WHERE email = 'demo@agri-smart.go');

-- 6. Add a function to reset all data
CREATE OR REPLACE FUNCTION reset_all_data(admin_email text)
RETURNS void AS $$
BEGIN
    -- This order respects foreign key constraints.
    DELETE FROM public.order_items;
    DELETE FROM public.farm_activities;
    DELETE FROM public.iot_devices;
    DELETE FROM public.sales_orders;
    DELETE FROM public.financial_transactions;
    DELETE FROM public.assets;
    DELETE FROM public.receivables;
    DELETE FROM public.payables;
    DELETE FROM public.investment_projects;
    DELETE FROM public.risk_items;
    DELETE FROM public.supply_items;
    DELETE FROM public.plots;
    DELETE FROM public.products;
    DELETE FROM public.customers;
    DELETE FROM public.employees;

    -- Delete all users except for the admin invoking this function
    DELETE FROM public.users WHERE email <> admin_email;

    -- Reset sequences to start from 1 again
    ALTER SEQUENCE employee_id_seq RESTART WITH 1;
END;
$$ LANGUAGE plpgsql;
`;

const StepCard: React.FC<{ number: number; title: string; children: React.ReactNode }> = ({ number, title, children }) => (
    <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md border dark:border-gray-700">
        <div className="flex items-center mb-4">
            <div className="flex-shrink-0 bg-green-100 dark:bg-green-900/50 text-green-600 dark:text-green-400 rounded-full h-10 w-10 flex items-center justify-center font-bold text-lg">
                {number}
            </div>
            <h3 className="ml-4 text-xl font-semibold text-gray-800 dark:text-gray-100">{title}</h3>
        </div>
        <div className="pl-14">{children}</div>
    </div>
);

const SqlSyntaxHighlighter: React.FC<{ code: string }> = ({ code }) => {
    const highlightedCode = useMemo(() => {
        // Simple HTML escaping
        let processedCode = code
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;');

        // Comments (--)
        processedCode = processedCode.replace(/(--.*)/g, '<span class="text-green-600 dark:text-green-500 italic">$1</span>');
        
        // Strings ('...')
        processedCode = processedCode.replace(/('[\s\S]*?')/g, '<span class="text-orange-600 dark:text-orange-400">$1</span>');
        
        // Data Types
        const types = ['text', 'uuid', 'bigint', 'timestamptz', 'date', 'numeric', 'jsonb', 'boolean', 'integer', 'enum'];
        const typesRegex = new RegExp(`\\b(${types.join('|')})\\b`, 'gi');
        processedCode = processedCode.replace(typesRegex, '<span class="text-teal-600 dark:text-teal-400">$1</span>');

        // Keywords
        const keywords = [
            'SELECT', 'FROM', 'WHERE', 'INSERT', 'INTO', 'VALUES', 'UPDATE', 'SET', 'DELETE',
            'CREATE', 'TABLE', 'ALTER', 'DROP', 'PRIMARY', 'KEY', 'FOREIGN', 'REFERENCES',
            'IF', 'NOT', 'EXISTS', 'DEFAULT', 'CONSTRAINT', 'UNIQUE', 'ON', 'CASCADE', 'NULL',
            'AS', 'DO', 'BEGIN', 'END', 'EXCEPTION', 'WHEN', 'THEN', 'LANGUAGE', 'plpgsql',
            'RETURNS', 'SEQUENCE', 'NEXTVAL', 'LPAD', 'OR', 'REPLACE', 'FUNCTION',
            'ENABLE', 'ROW', 'LEVEL', 'SECURITY', 'POLICY', 'FOR', 'ALL', 'TO', 'USING', 'WITH', 'CHECK',
            'identity', 'generated', 'by', 'as'
        ];
        const keywordsRegex = new RegExp(`\\b(${keywords.join('|')})\\b`, 'gi');
        processedCode = processedCode.replace(keywordsRegex, '<span class="text-blue-600 dark:text-blue-400 font-semibold">$1</span>');

        // Functions and special values
        processedCode = processedCode.replace(/\b(public|uuid_generate_v4|now|lpad|nextval|reset_all_data|jsonb_build_object|true|false|authenticated)\b/g, '<span class="text-purple-500 dark:text-purple-400">$1</span>');

        // Numbers
        processedCode = processedCode.replace(/(\b\d+\b)/g, '<span class="text-cyan-600 dark:text-cyan-400">$1</span>');

        return processedCode;
    }, [code]);

    return (
        <pre className="bg-gray-50 dark:bg-gray-900 text-gray-800 dark:text-gray-300 p-4 rounded-lg overflow-x-auto text-sm leading-relaxed">
            <code dangerouslySetInnerHTML={{ __html: highlightedCode }} />
        </pre>
    );
};

const DatabaseSetupPage: React.FC = () => {
    const [copySuccess, setCopySuccess] = useState('');

    const handleCopy = () => {
        navigator.clipboard.writeText(sqlScript).then(() => {
            setCopySuccess('คัดลอกสคริปต์เรียบร้อยแล้ว!');
            setTimeout(() => setCopySuccess(''), 2000);
        }, () => {
            setCopySuccess('ไม่สามารถคัดลอกได้');
            setTimeout(() => setCopySuccess(''), 2000);
        });
    };

    return (
        <div className="bg-gray-50 dark:bg-gray-900 p-4 md:p-8 text-gray-800 dark:text-gray-200 min-h-screen">
            <div className="max-w-4xl mx-auto">
                <h1 className="text-3xl md:text-4xl font-bold mb-2 text-center text-gray-800 dark:text-gray-100">เริ่มต้นใช้งาน (Getting Started)</h1>
                <p className="text-gray-600 dark:text-gray-400 mb-8 text-center">กรุณาทำตามขั้นตอนทั้งหมดเพื่อตั้งค่าฐานข้อมูลและผู้ใช้งานสำหรับแอปพลิเคชัน</p>
    
                <div className="bg-yellow-50 dark:bg-yellow-900/30 border-l-4 border-yellow-400 p-4 rounded-r-lg mb-8 shadow">
                    <div className="flex">
                        <div className="py-1"><svg className="fill-current h-6 w-6 text-yellow-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zM9 11v4h2v-4H9zm0-4h2v2H9V7z"/></svg></div>
                        <div><p className="font-bold text-yellow-800 dark:text-yellow-200">สำคัญมาก</p><p className="text-sm text-yellow-700 dark:text-yellow-300">ต้องทำทั้ง 3 ขั้นตอนตามลำดับ สคริปต์นี้สามารถรันซ้ำได้โดยไม่เกิดข้อผิดพลาด</p></div>
                    </div>
                </div>

                <div className="space-y-8">
                    <StepCard number={1} title="สร้างผู้ใช้งานสำหรับล็อกอิน">
                        <p className="text-gray-600 dark:text-gray-400 mb-4">ขั้นตอนนี้จะสร้างผู้ใช้ในระบบ Authentication ของ Supabase เพื่อให้คุณสามารถล็อกอินเข้าแอปพลิเคชันได้</p>
                        <ol className="list-decimal list-inside text-gray-700 dark:text-gray-300 space-y-2">
                            <li>ไปที่โปรเจกต์ Supabase และเลือกเมนู <code className="bg-gray-200 dark:bg-gray-700 px-1.5 py-0.5 rounded">Authentication</code></li>
                            <li>คลิกที่ปุ่ม <code className="bg-gray-200 dark:bg-gray-700 px-1.5 py-0.5 rounded">+ Add user</code></li>
                            <li>ในช่อง Email, กรอก: <code className="bg-gray-200 dark:bg-gray-700 px-1.5 py-0.5 rounded">demo@agri-smart.go</code></li>
                            <li>ในช่อง Password, กรอกรหัสผ่าน (เช่น <code className="bg-gray-200 dark:bg-gray-700 px-1.5 py-0.5 rounded">123456</code>)</li>
                            <li>**(สำคัญ)** ปิดสวิตช์ <code className="bg-gray-200 dark:bg-gray-700 px-1.5 py-0.5 rounded">Enable email confirmation</code></li>
                            <li>คลิกปุ่ม <code className="bg-green-200 dark:bg-green-700 px-1.5 py-0.5 rounded text-green-800 dark:text-green-100 font-bold">Add user</code></li>
                        </ol>
                    </StepCard>
                    
                    <StepCard number={2} title="สร้างตารางและข้อมูล (SQL Script)">
                         <p className="text-gray-600 dark:text-gray-400 mb-4">ขั้นตอนนี้จะสร้างตารางทั้งหมดที่แอปพลิเคชันต้องใช้ รวมถึงข้อมูลเริ่มต้นบางส่วน</p>
                         <ol className="list-decimal list-inside text-gray-700 dark:text-gray-300 space-y-2 mb-4">
                            <li>ในเมนูด้านซ้ายของ Supabase, เลือก <code className="bg-gray-200 dark:bg-gray-700 px-1.5 py-0.5 rounded">SQL Editor</code></li>
                            <li>คลิกที่ <code className="bg-gray-200 dark:bg-gray-700 px-1.5 py-0.5 rounded">+ New query</code></li>
                            <li>คัดลอกสคริปต์ทั้งหมดด้านล่างนี้ไปวางในหน้าต่าง Editor</li>
                            <li>กดปุ่ม <code className="bg-green-200 dark:bg-green-700 px-1.5 py-0.5 rounded text-green-800 dark:text-green-100 font-bold">RUN</code></li>
                        </ol>
                        <div className="relative">
                            <button onClick={handleCopy} className="absolute top-3 right-3 px-3 py-1 bg-gray-600 text-white text-xs font-semibold rounded-md hover:bg-gray-900 dark:bg-gray-200 dark:text-gray-800 dark:hover:bg-white transition-colors">{copySuccess ? copySuccess : 'คัดลอก'}</button>
                            <SqlSyntaxHighlighter code={sqlScript} />
                        </div>
                    </StepCard>

                    <StepCard number={3} title="ตั้งค่า Storage สำหรับรูปภาพ">
                         <p className="text-gray-600 dark:text-gray-400 mb-4">ขั้นตอนนี้จำเป็นเพื่อให้ฟังก์ชันอัปโหลดรูปโปรไฟล์ผู้ใช้งานทำงานได้</p>
                         <ol className="list-decimal list-inside text-gray-700 dark:text-gray-300 space-y-2">
                             <li>ไปที่เมนู <code className="bg-gray-200 dark:bg-gray-700 px-1.5 py-0.5 rounded">Storage</code></li>
                             <li>คลิก <code className="bg-gray-200 dark:bg-gray-700 px-1.5 py-0.5 rounded">+ Create a new bucket</code></li>
                             <li>ในช่อง Bucket name, กรอก: <code className="bg-gray-200 dark:bg-gray-700 px-1.5 py-0.5 rounded">avatars</code></li>
                             <li>ติ๊กที่ช่อง <code className="bg-gray-200 dark:bg-gray-700 px-1.5 py-0.5 rounded">This bucket is public</code></li>
                             <li>คลิก <code className="bg-green-200 dark:bg-green-700 px-1.5 py-0.5 rounded text-green-800 dark:text-green-100 font-bold">Create bucket</code></li>
                             <li>ไปที่แท็บ <code className="bg-gray-200 dark:bg-gray-700 px-1.5 py-0.5 rounded">Policies</code> ของ bucket 'avatars' คลิก <code className="bg-gray-200 dark:bg-gray-700 px-1.5 py-0.5 rounded">+ New Policy</code> และเลือก <code className="bg-gray-200 dark:bg-gray-700 px-1.5 py-0.5 rounded">Enable insert access for authenticated users</code></li>
                         </ol>
                    </StepCard>
                </div>
                
                <div className="text-center mt-12">
                    <Link to="/login" className="px-6 py-3 bg-green-600 text-white font-semibold rounded-lg hover:bg-green-700 transition-colors shadow-md hover:shadow-lg transform hover:-translate-y-0.5">
                        ตั้งค่าเสร็จแล้ว? กลับไปหน้าล็อกอิน
                    </Link>
                </div>
            </div>
        </div>
    );
};

export default DatabaseSetupPage;
